name: Pull Inventory Feed

on:
  workflow_dispatch: {}
  schedule:
    # Every 2 hours (UTC). You can change later.
    - cron: "5 */2 * * *"

permissions:
  contents: write

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch + snapshot
        run: python scripts/pull_inventory.py

      - name: Commit & push (only if changed)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "inventory-bot"
            git config user.email "inventory-bot@users.noreply.github.com"
            git add data/latest data/snapshots data/manifest.csv
            git commit -m "Inventory snapshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
